### ISSUE TITLE
Fix check of HTTP status added in 12516dd

### ISSUE THREAD

**Issue by FGasper** [CpanelInc/cPanel-PublicAPI#22]
In 12516dd6554309d5402bf5a4c1b9ed86824f806c a check was added that should have been against HTTP::Tiny’s `status` but was instead done against `reason`.

https://github.com/CpanelInc/cPanel-PublicAPI/commit/12516dd6554309d5402bf5a4c1b9ed86824f806c#r33460020

**Comment by drmuey** [comment]
looks like this was fixed in master, closing
