### ISSUE TITLE
Which version of WHM API is used?

### ISSUE THREAD

**Issue by rwp0** [CpanelInc/cPanel-PublicAPI#39]
The [`whm_api`](https://metacpan.org/pod/cPanel::PublicAPI#Querying-the-xml-api-whm_api()) section doesn't describe the API version it is using.

According to cPanel docs there are two versions of the WHM API available:

- [WHM API 0](https://documentation.cpanel.net/display/DD/Guide+to+WHM+API+0)
- [WHM API 1](https://documentation.cpanel.net/display/DD/Guide+to+WHM+API+1)

The former is deprecated, while the latter is current.

Hence I wanted to know which one I'm using and which documentation should I refer therefore to.

Thanks

**Comment by cpanelrikus** [comment]
This is answered in [the documentation for cPanel::PublicAPI](https://metacpan.org/pod/cPanel::PublicAPI#Querying-the-xml-api-whm_api()):

```By default, WHM API v1 is used. If, for legacy reasons, you need to use v0, please set the api.version key to 0 in the formdata parameter.```

I've verified that this information is accurate.

**Comment by rwp0** [comment]
Ah yes, thanks @cpanelrikus. I'm sorry, I've somehow missed that part 🙂
